# Generated by Django 4.1.7 on 2023-02-26 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='code',
            field=models.CharField(default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referred_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
