# Generated by Django 4.1.7 on 2023-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_referralcode_code_alter_referralcode_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_ref_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
